### ISSUE TITLE
Yellow Scrap Bags

### ISSUE THREAD

**Issue by belathus** [belathus/Wanderlust#19]
#### Common
* [x] Pressure Tube
* [x] Compressed Iron
* [x] Turbine Blade
* [x] Programming Puzzle Piece
* [x] Transistor
* [x] Capacitor
* [x] STOP! Worm
* [x] Nuke Virus
* [x] Pneumatic Cylinder
* [x] Heat Pipe
#### Uncommon
* [x] Pressure Gauge
* [x] Logistics Core
* [x] Transfer Gadget
* [x] Spawner Agitator
* [x] Minigun Ammo
#### Rare
* [x] Micro Missiles
* [x] Broken Spawner

**Comment by TBone311xXx** [comment]
checkity check ✅
